CREATE DATABASE IF NOT EXISTS today_friday
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE today_friday;

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  payment_id VARCHAR(128) NOT NULL UNIQUE,
  provider VARCHAR(32) NOT NULL DEFAULT 'stub',
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  amount DECIMAL(10,2) NOT NULL DEFAULT 99.00,
  currency CHAR(3) NOT NULL DEFAULT 'RUB',
  payment_url TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paid_at TIMESTAMP NULL DEFAULT NULL,
  INDEX idx_payments_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS checks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  payment_id VARCHAR(128) NOT NULL,
  is_friday TINYINT(1) NOT NULL,
  checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_checks_payment (payment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
